In [1]:
import pandas as pd

In [6]:
datatype = {'index': str,
            'round': str, 
            'session': str,
            'line_part': str,
            'participant': str,
            'stimuli_image': str,
            'stimuli_text': str,
            'duration': 'int64',
            'x_cord': 'float64',
            'y_cord': 'float64',
            'aoi_x': 'float64',
            'aoi_y': 'float64', 
            'aoi_width': 'float64', 
            'aoi_height': 'float64',
            'token': str,
            'length': 'int64'}

df = pd.read_csv('datasets/processed_result.csv', dtype=datatype)

In [8]:
df = df.drop(columns=["Unnamed: 0", "Unnamed: 0.1"])

In [15]:
df['line'] = df['line_part'].apply(lambda line_part: line_part.split()[1])

In [18]:
df = df.set_index('index')

In [19]:
df.head()

,round,session,participant,line_part,stimuli_image,stimuli_text,timestamp,duration,x_cord,y_cord,aoi_x,aoi_y,aoi_width,aoi_height,token,length,line
index,,,,,,,,,,,,,,,,,
11001_0,1,1,001,line 12 part 3,TEX_R1S1_bg.png,TEX_R1S1_text.txt,263.0,120,722.360000,488.112500,700.5,467.0,102.0,32.0,brought,7,12
11001_1,1,1,001,line 13 part 3,TEX_R1S1_bg.png,TEX_R1S1_text.txt,263.0,120,722.360000,488.112500,708.5,500.0,96.0,32.0,broker,6,13
11001_2,1,1,001,line 12 part 3,TEX_R1S1_bg.png,TEX_R1S1_text.txt,519.0,255,736.400394,491.933725,700.5,467.0,102.0,32.0,brought,7,12
11001_3,1,1,001,line 13 part 3,TEX_R1S1_bg.png,TEX_R1S1_text.txt,519.0,255,736.400394,491.933725,708.5,500.0,96.0,32.0,broker,6,13
11001_4,1,1,001,line 12 part 4,TEX_R1S1_bg.png,TEX_R1S1_text.txt,698.0,161,809.180746,494.226708,803.5,467.0,28.0,32.0,to,2,12

In [24]:
from tqdm import tqdm
from word import Word

In [25]:
lexicon = {}

participants = {}

for row in tqdm(df.iterrows()):
    
    index = row[0]
    cols = row[1]
    
    round_id = index[0]
    session_id = index[1]
    file_id = round_id + session_id
    
    participant_id = index[2:5]
    
    line_part = cols['line_part']
    _, line_id, _, part_id = line_part.split()
    
    timestamp = cols['timestamp']
    duration = cols['duration']
    length = cols['length']
    frequency = 0
    predict = 0
    level = 0
    
    token = cols['token']
    
    key = f'{file_id}_{line_id}_{part_id}_{participant_id}'
    
    if lexicon.get(key, 0) == 0:
        lexicon[key] = Word(file_id, line_part, token)
        
    lexicon[key].add(participant=participant_id, 
                     duration=duration, 
                     start_time=timestamp, 
                     length=length, 
                     freq=frequency, 
                     predict=predict,
                     level=level)
    
    if participants.get(file_id, 0) == 0:
        participants[file_id] = []
    
    if participant_id not in participants[file_id]:
        participants[file_id].append(participant_id)

537666it [00:39, 13656.41it/s]

In [36]:
list(lexicon.values())[4]._start_times

[778, 14333, 15686, 42392]

In [27]:
headers = ['file',
           'line',
           'tokens',
           'subject',
           'duration',
           'SFD',
           'FFD',
           'GD',
           'TT',
           'PrF',
           'Pr1',
           'Pr2',
           'PrS',
           'length',
           'wpm']

result = pd.DataFrame(columns=headers)

In [41]:
sentences = dict()

for key, word in tqdm(lexicon.items()):
    file, line, part, subject = key.split('_')
    
    sentence_key = file + '_' + line + '_' + subject

    if sentences.get(sentence_key, 0) == 0:
        sentences[sentence_key] = {}
    
    sentences[sentence_key][part] = word

100%|███████████████████████████████| 230091/230091 [00:00<00:00, 692179.74it/s]

In [52]:
np.array(list(sentences.items())[0][-1].keys())[0]

IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

In [47]:
import numpy as np

In [60]:
import numpy as np

for key, sentence in tqdm(sentences.items()):
    file, line, subject = key.split('_')
    
    min_word_key = np.sort(list(sentence.keys()))[0]
    max_word_key = np.sort(list(sentence.keys()))[-1]
    
    tokens = ""
    duration = sentence[max_word_key]._start_times[0] - sentence[min_word_key]._start_times[0]
    
    SFD = np.mean([word.single_fix_duration() / word.get_leng() for key, word in sentence.items()])
    FFD = np.mean([word.first_fix_duration() / word.get_leng() for key, word in sentence.items()])
    GD = np.mean([word.gaze_duration() / word.get_leng() for key, word in sentence.items()])
    TT = np.mean([word.total_time() / word.get_leng() for key, word in sentence.items()])
    PrF = np.mean([word.fix_probability() for key, word in sentence.items()])
    Pr1 = np.mean([word.prob_of_one_fix() for key, word in sentence.items()])
    Pr2 = np.mean([word.prob_of_2_or_more_fix() for key, word in sentence.items()])
    PrS = np.mean([word.prob_of_skip() for key, word in sentence.items()])
    
    length = 0
    wpm = 0
    
    values = [file, line, tokens, subject, duration, SFD, FFD, GD, TT, PrF, Pr1, Pr2, PrS, length, wpm]
    
    dic = dict(zip(headers, values))
    
    result = result.append(dic, ignore_index=True)

 37%|█████████████▏                      | 15385/42144 [01:36<03:19, 134.01it/s]/var/folders/3h/wbvtqh2d001gvnsysbmn8c3w0000gs/T/ipykernel_56984/1804764806.py:13: RuntimeWarning: divide by zero encountered in double_scalars
  FFD = np.mean([word.first_fix_duration() / word.get_leng() for key, word in sentence.items()])
/var/folders/3h/wbvtqh2d001gvnsysbmn8c3w0000gs/T/ipykernel_56984/1804764806.py:14: RuntimeWarning: divide by zero encountered in double_scalars
  GD = np.mean([word.gaze_duration() / word.get_leng() for key, word in sentence.items()])
/var/folders/3h/wbvtqh2d001gvnsysbmn8c3w0000gs/T/ipykernel_56984/1804764806.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  TT = np.mean([word.total_time() / word.get_leng() for key, word in sentence.items()])
 38%|█████████████▌                      | 15918/42144 [01:40<03:21, 130.39it/s]/var/folders/3h/wbvtqh2d001gvnsysbmn8c3w0000gs/T/ipykernel_56984/1804764806.py:12: RuntimeWarning: divide by zero encountered in double_scalars
  SFD = np.mean([word.single_fix_duration() / word.get_leng() for key, word in sentence.items()])
100%|████████████████████████████████████| 42144/42144 [04:52<00:00, 144.24it/s]

In [66]:
result

,file,line,tokens,subject,duration,SFD,FFD,GD,TT,PrF,Pr1,Pr2,PrS,length,wpm
0,11,12,,001,1858,NaN,28.482937,28.482937,107.370437,0.00,0.000000,0.000000,1.00,0,0
1,11,13,,001,-547,NaN,39.660000,39.660000,80.873333,0.00,0.000000,0.000000,1.00,0,0
2,11,2,,001,1456,NaN,52.490136,52.490136,136.861905,0.00,0.000000,0.000000,1.00,0,0
3,11,3,,001,688,NaN,61.333333,61.333333,123.916667,0.00,0.000000,0.000000,1.00,0,0
4,11,4,,001,1071,NaN,48.252381,48.252381,90.100000,0.00,0.000000,0.000000,1.00,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
44482,92,20,,314,-744,NaN,79.569444,79.569444,115.150926,0.07,0.035000,0.035000,0.93,0,0
44483,92,21,,314,1528,NaN,80.800000,80.800000,102.800000,0.07,0.056000,0.014000,0.93,0,0
44484,92,23,,314,1140,NaN,46.873333,46.873333,73.263333,0.07,0.028000,0.042000,0.93,0,0
44485,92,24,,314,-294,NaN,64.219444,64.219444,106.519444,0.07,0.046667,0.023333,0.93,0,0
44486,92,25,,314,-698,NaN,115.586538,115.586538,282.519231,0.07,0.000000,0.070000,0.93,0,0